DEBUG 2025-07-02 20:21:21.008 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-02 20:21:21.009 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-02 20:21:21.009 UTC: 	 Not using Singularity
DEBUG 2025-07-02 20:21:21.009 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-02 20:21:21.009 UTC: 	 Executing command: 'status'
DEBUG 2025-07-02 20:21:21.009 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-02 20:21:21.015 UTC: 	 Error: Run3_D0_Data_miniAOD/crab_Run3_D0_Data_miniAOD/ is not a valid CRAB project directory.
ERROR 2025-07-02 20:21:21.015 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: Run3_D0_Data_miniAOD/crab_Run3_D0_Data_miniAOD/ is not a valid CRAB project directory.
INFO 2025-07-02 20:21:21.070 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab.log
DEBUG 2025-07-11 04:43:30.764 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 04:43:30.764 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 04:43:30.764 UTC: 	 Not using Singularity
DEBUG 2025-07-11 04:43:30.764 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 04:43:30.764 UTC: 	 Executing command: 'status'
DEBUG 2025-07-11 04:43:30.765 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-11 04:43:30.767 UTC: 	 Error: --long is not a valid CRAB project directory.
ERROR 2025-07-11 04:43:30.767 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: --long is not a valid CRAB project directory.
INFO 2025-07-11 04:43:30.770 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab.log
DEBUG 2025-07-11 04:43:47.125 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 04:43:47.125 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 04:43:47.125 UTC: 	 Not using Singularity
DEBUG 2025-07-11 04:43:47.125 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 04:43:47.126 UTC: 	 Executing command: 'status'
DEBUG 2025-07-11 04:43:47.126 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-11 04:43:47.128 UTC: 	 Error: --long is not a valid CRAB project directory.
ERROR 2025-07-11 04:43:47.128 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: --long is not a valid CRAB project directory.
INFO 2025-07-11 04:43:47.132 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab.log
